name: dask-kubernetes-test
channels:
  - defaults
  - conda-forge
dependencies:
  - flake8
  - ipywidgets
  - dask=1.2.2
  - distributed=1.28.1
  - nomkl
  - pytest
  - black
  - python=3.7
  - pyyaml
  - pip:
    - kubernetes==9
    - git+https://github.com/dask/distributed.git
    - git+https://github.com/dask/dask.git
